set(CTEST_DROP_METHOD "https")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=${CTEST_PROJECT_NAME}")
set(CTEST_DROP_SITE_CDASH TRUE)

if(GITHUB_ACTIONS)
  set(_auth_token "$ENV{CDASH_TOKEN}")
else()
  file(READ "${AUTH_TOKEN_FILE}" _rawtoken)
  string(STRIP "${_rawtoken}" _auth_token)
endif()
string(TIMESTAMP CURRENT_DATE "%Y%m%d")
set(CTEST_BUILD_NAME "${CURRENT_DATE}${GH_COMMIT_HASH}")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_CONFIGURATION "Debug")
if(GITHUB_ACTIONS) # for others, run steps separately (enables normal Spack use)
  set(CTEST_BINARY_DIRECTORY build)
  ctest_empty_binary_directory(${CTEST_BINARY_DIRECTORY})
endif()
ctest_start(MemoryCheck)
if(CMAKE_C_COMPILER_ID STREQUAL GNU)
  set(CONFIG_OPTIONS "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=--coverage -DCMAKE_Fortran_FLAGS=--coverage ${CONFIG_OPTIONS}")
endif()

# When PROFILING_INCLUDE_FILE is set (via the ci-cdash action's `profiling`
# input), forward the CMake options needed to activate ci-profile-tests'
# Profiling.cmake in the tested project's own configure step. The project's
# CMakeLists.txt must opt in with:
#   if(DEFINED PROFILING_INCLUDE_FILE)
#     include("${PROFILING_INCLUDE_FILE}")
#   endif()
if(PROFILING_INCLUDE_FILE)
  set(CONFIG_OPTIONS
    "-DENABLE_PROFILING=ON -DPROFILING_TOOL=gprof -DPROFILING_ANALYSIS=ON -DENABLE_CDASH=ON -DPROFILING_INCLUDE_FILE=${PROFILING_INCLUDE_FILE} ${CONFIG_OPTIONS}")
endif()
string(REPLACE " " ";" CONFIG_OPTIONS "${CONFIG_OPTIONS}")
ctest_configure(BUILD "${CTEST_BINARY_DIRECTORY}" OPTIONS "${CONFIG_OPTIONS}")
ctest_build(BUILD "${CTEST_BINARY_DIRECTORY}" CONFIGURATION Debug FLAGS "VERBOSE=1")
find_program(VALGRIND_EXECUTABLE valgrind)
set(CTEST_MEMORYCHECK_COMMAND ${VALGRIND_EXECUTABLE})
set(CTEST_MEMORYCHECK_COMMAND_OPTIONS "--trace-children=yes")
if(PROFILING_INCLUDE_FILE)
  ctest_memcheck(BUILD "${CTEST_BINARY_DIRECTORY}" EXCLUDE_LABEL "profiling_analysis|gprof_instrumented")
  ctest_test(BUILD "${CTEST_BINARY_DIRECTORY}" INCLUDE_LABEL "gprof_instrumented")
  ctest_test(BUILD "${CTEST_BINARY_DIRECTORY}" INCLUDE_LABEL "profiling_analysis")
else()
  ctest_memcheck(BUILD "${CTEST_BINARY_DIRECTORY}")
endif()
if(CMAKE_C_COMPILER_ID STREQUAL GNU)
  set(CTEST_COVERAGE_COMMAND "gcov")
  set(CTEST_CUSTOM_COVERAGE_EXCLUDE "tests/.*;test/*;build/*")
  ctest_coverage(BUILD "${CTEST_SOURCE_DIRECTORY}")
endif()
ctest_submit(HTTPHEADER "Authorization: Bearer ${_auth_token}")
